name: sb_env
channels:
  - conda-forge
  - conda
  - defaults
dependencies:
  # Dependencies
  - osmnx>=1.6.0
  - geopandas
  - rasterio
  - shapely
  - numba
  - tqdm
  - contextily
  - ruamel.yaml
  - pyarrow
  - seaborn
  - psutil
  - typing-extensions