name: sb_env
channels:
  - conda-forge
  - conda
  - defaults
dependencies:
  # Dependencies
  - osmnx
  - geopandas
  - rasterio
  - shapely
  - numba
  - tqdm
  - contextily
  - ruamel.yaml
  - pyarrow
  - seaborn
  - psutil
  - typing-extensions
  - rasterstats  # only used in one reference notebook
  - momepy  # only used in one reference notebook
  # Code Quality
  - blackd
  - isort
  - pylint
  # Testing
  - pytest
  - pytest-cov
  - coverage
  # Documentation
  - sphinx
  - numpydoc
  - myst-nb
  - sphinx-book-theme