name: Docs

on:
  push:
    branches:
      - main
    paths:
      - 'superblockify/**'
      - 'docs/**'
      - 'logging.cfg'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  generate-deploy-docs:
    strategy:
      matrix:
        python-version: ["3.12"]
        os: [ubuntu-latest]
    name: Generate documentation
    runs-on: ${{ matrix.os }}
    environment:
      name: Deploy to github pages
      url: ${{ steps.deployment.outputs.page_url }}
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Get week number
        run: echo "WEEK=$(date +'%V')" >> $GITHUB_ENV

      - name: Set up Python ${{ matrix.python-version }}
        uses: mamba-org/setup-micromamba@v1
        with:
          create-args: python=${{ matrix.python-version }}
          environment-file: environment.yml
          cache-environment: true
          cache-environment-key: W${{ env.WEEK }}

      - name: Add Notebook Kernel
        run: python -m ipykernel install --user --name sb_env --display-name "Python (sb_env)"

      - name: Generating .rst files
        run: sphinx-apidoc -o docs/api/ superblockify/
      - name: Generating html
        run: sphinx-build docs public -b dirhtml

      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload generated html
          path: 'public/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1