name: Lint

on: [ push, pull_request ]

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup and activate Anaconda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: OSMnxPyrLab
          environment-file: environment.yaml
      - name: Show environment infos
        run: |
          conda info
          conda list

      - name: Run Linters
        uses: wearerequired/lint-action@v2
        with:
          auto_fix: true
          black: true
          black_auto_fix: true
          black_dir: /../../../../../usr/share/miniconda/envs/OSMnxPyrLab/bin/
          pylint: true
          pylint_auto_fix: false
          pylint_dir: /../../../../../usr/share/miniconda/envs/OSMnxPyrLab/bin/
          git_name: ${GITHUB_ACTOR}
          git_email: ${GITHUB_ACTOR}@users.noreply.github.com