name: Lint

on: [ push, pull_request ]

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup Anaconda environment
        uses: fdiblen/anaconda-action@master
        id: step1
        with:
          envFileName: 'environment.yaml'
          channels: conda-forge
      - name: Get the Conda and Python version
        run: echo "Using conda version ${{ steps.step1.outputs.conda_version }} and
          python version python version is ${{ steps.step1.outputs.python_version }}"

      - name: Run Linters
        uses: wearerequired/lint-action@v2
        with:
          auto_fix: true
          black: true
          black_auto_fix: true
          pylint: true
          pylint_auto_fix: false
          git_name: ${GITHUB_ACTOR}
          git_email: ${GITHUB_ACTOR}@users.noreply.github.com