name: Test

on: [ push, pull_request ]

jobs:
  run-tests:
    name: Run test coverage
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup and activate Anaconda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: OSMnxPyrLab
          environment-file: environment.yml

      - name: Show environment infos
        run: |
          conda info
          conda list

      - name: Run tests with coverage
        run: pytest --cov=superblockify tests/

      - name: Coverage comment
        id: coverage_comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Store Pull Request comment to be posted
        uses: actions/upload-artifact@v3
        if: steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true'
        with:
          name: python-coverage-comment-action
          path: python-coverage-comment-action.txt